name: Run Job Scraper

on:
  schedule:
    - cron: "0 0 * * *" # every day at 12 AM UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npx tsc

      - name: Install Chromium dependencies
        run: sudo apt-get update && sudo apt-get install -y \
          gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 \
          libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 \
          libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 \
          libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
          libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 \
          libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation \
          libnss3 lsb-release xdg-utils wget chromium-browser

      - name: Run scraper
        run: node dist/scraper.js

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: jobs
          path: dist/jobs.json
