name: Job Scraper

on:
  schedule:
    - cron: "0 18 * * *" # Runs daily at 12:00 AM IST (18:00 UTC)
  workflow_dispatch: # allows manual run from GitHub Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc

      - name: Run scraper
        run: node dist/scraper.js

      - name: Upload jobs.json artifact
        uses: actions/upload-artifact@v4
        with:
          name: jobs-output
          path: jobs.json
