name: Nightly Job Scraper

on:
  schedule:
    - cron: '0 0 * * *' # Every day at 12 AM UTC
  workflow_dispatch: # Allows manual runs

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: npx ts-node scraper.ts

      - name: Save jobs.json as artifact
        uses: actions/upload-artifact@v3
        with:
          name: jobs
          path: jobs.json
