name: Run Job Scraper

on:
  schedule:
    - cron: "0 0 * * *" # every day at 12 AM UTC
  workflow_dispatch: # manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc

      - name: Run scraper
        run: node dist/scraper.js

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: jobs
          path: dist/jobs.json
