name: Run Job Scraper

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at 12 AM UTC
  workflow_dispatch: # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: npx ts-node scraper.ts

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: jobs
          path: jobs.json
