name: Run Job Scraper

on:
  schedule:
    # Runs every day at 12:00 AM UTC (adjust later for IST if needed)
    - cron: "0 0 * * *"
  workflow_dispatch:  # lets you trigger manually from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: npx ts-node scraper.ts

      - name: Upload jobs.json artifact
        uses: actions/upload-artifact@v3
        with:
          name: jobs
          path: jobs.json
